=== christopherdavies2/automation_test_template/src/test/resources/schemas/user_by_id.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "id",
    "createdAt",
    "name",
    "isPartTime",
    "locationId",
    "favLanguages",
    "address"
  ],
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "string",
      "title": "The Id Schema",
      "default": "",
      "examples": [
        "1"
      ],
      "pattern": "^(.*)$"
    },
    "createdAt": {
      "$id": "#/properties/createdAt",
      "type": "string",
      "title": "The Createdat Schema",
      "default": "",
      "examples": [
        "2019-03-09T20:15:02.098Z"
      ],
      "pattern": "^(.*)$"
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "The Name Schema",
      "default": "",
      "examples": [
        "Norbert Wiza"
      ],
      "pattern": "^(.*)$"
    },
    "isPartTime": {
      "$id": "#/properties/isPartTime",
      "type": "boolean",
      "title": "The Isparttime Schema",
      "default": false,
      "examples": [
        false
      ]
    },
    "locationId": {
      "$id": "#/properties/locationId",
      "type": "integer",
      "title": "The Locationid Schema",
      "default": 0,
      "examples": [
        16
      ]
    },
    "favLanguages": {
      "$id": "#/properties/favLanguages",
      "type": "array",
      "title": "The Favlanguages Schema",
      "items": {
        "$id": "#/properties/favLanguages/items",
        "type": "string",
        "title": "The Items Schema",
        "default": "",
        "examples": [
          "java",
          "ruby",
          "python"
        ],
        "pattern": "^(.*)$"
      }
    },
    "address": {
      "$id": "#/properties/address",
      "type": "object",
      "title": "The Address Schema",
      "required": [
        "street",
        "city",
        "postcode"
      ],
      "properties": {
        "street": {
          "$id": "#/properties/address/properties/street",
          "type": "string",
          "title": "The Street Schema",
          "default": "",
          "examples": [
            "11 A street"
          ],
          "pattern": "^(.*)$"
        },
        "city": {
          "$id": "#/properties/address/properties/city",
          "type": "string",
          "title": "The City Schema",
          "default": "",
          "examples": [
            "Leeds"
          ],
          "pattern": "^(.*)$"
        },
        "postcode": {
          "$id": "#/properties/address/properties/postcode",
          "type": "string",
          "title": "The Postcode Schema",
          "default": "",
          "examples": [
            "LS1 1A1"
          ],
          "pattern": "^(.*)$"
        }
      }
    }
  }
}

=== christopherdavies2/automation_test_template/src/test/resources/expected-responses/users_response.json
[
    {
        "id": "1",
        "createdAt": "2019-03-09T20:15:02.098Z",
        "name": "Norbert Wiza",
        "isPartTime": false,
        "locationId": 16,
        "favLanguages": [
            "java",
            "ruby",
            "python"
        ],
        "address": {
            "street": "11 A street",
            "city": "Leeds",
            "postcode": "LS1 1A1"
        }
    },
    {
        "id": "2",
        "createdAt": "2018-12-22T00:44:22.800Z",
        "name": "Alene Schimmel",
        "isPartTime": false,
        "locationId": 95,
        "favLanguages": [
            "java",
            "ruby",
            "python"
        ],
        "address": {
            "street": "12 A street",
            "city": "Leeds",
            "postcode": "LS1 1A2"
        }
    },
    {
        "id": "3",
        "createdAt": "2018-11-25T09:33:58.345Z",
        "name": "Darius Jast",
        "isPartTime": false,
        "locationId": 1,
        "favLanguages": [
            "java",
            "ruby",
            "python"
        ],
        "address": {
            "street": "13 A street",
            "city": "Leeds",
            "postcode": "LS1 1A3"
        }
    },
    {
        "id": "4",
        "createdAt": "2019-07-18T09:41:08.675Z",
        "name": "Amani Vandervort",
        "isPartTime": false,
        "locationId": 67,
        "favLanguages": [
            "java",
            "ruby",
            "python"
        ],
        "address": {
            "street": "14 A street",
            "city": "Leeds",
            "postcode": "LS1 1A4"
        }
    },
    {
        "id": "5",
        "createdAt": "2019-02-25T02:24:11.947Z",
        "name": "Cleveland Torp",
        "isPartTime": false,
        "locationId": 22,
        "favLanguages": [
            "java",
            "ruby",
            "python"
        ],
        "address": {
            "street": "15 A street",
            "city": "Leeds",
            "postcode": "LS1 1A5"
        }
    }
]
